"""add notes column to highlight table

Revision ID: e3137c28b6cb
Revises: 5b76079de295
Create Date: 2022-08-20 21:48:08.223812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3137c28b6cb'
down_revision = '5b76079de295'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('highlights', sa.Column('note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('highlights', 'note')
    # ### end Alembic commands ###
