"""create metadata table

Revision ID: ffb4865c0621
Revises: e3137c28b6cb
Create Date: 2022-08-26 22:11:14.563578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'ffb4865c0621'
down_revision = 'e3137c28b6cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata',
    sa.Column('google_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('authors', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('published_date', sa.String(), nullable=True),
    sa.Column('categories', sa.String(), nullable=True),
    sa.Column('cover_image', sa.BLOB(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sqlite.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('google_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metadata')
    # ### end Alembic commands ###
